In [2]:
%matplotlib inline
import sys, os
os.chdir('/fe4/blackhole-star/data/shredded')
os.environ['PYOPENGL_PLATFORM'] = 'egl'  # without this, OpenGL.EGL won't work.  Needed for batch render.

In [3]:
from OpenGL import EGL

In [4]:
import yt, yt_idv

In [4]:
import glob; glob.glob('*plt50')

['m1.0_p16_b2.0_300k_plt50']

In [5]:
ds = yt.load('m1.0_p16_b2.0_300k_plt50/multitidal_hdf5_plt_cnt_0200')
ds.force_periodicity()

yt : [INFO     ] 2022-03-24 14:29:24,729 Parameters: current_time              = 44232.23623685412
yt : [INFO     ] 2022-03-24 14:29:24,732 Parameters: domain_dimensions         = [8 8 8]
yt : [INFO     ] 2022-03-24 14:29:24,735 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2022-03-24 14:29:24,736 Parameters: domain_right_edge         = [8.95258e+13 8.95258e+13 8.95258e+13]
yt : [INFO     ] 2022-03-24 14:29:24,737 Parameters: cosmological_simulation   = 0


In [6]:
rc = yt_idv.render_context(engine='egl', gui=True, width=2048,height=2048)

In [7]:
ad = ds.all_data()
ad.max_level = 11

sg = rc.add_scene(ad, 'density', no_ghost=False)

In [8]:
im = rc.run()


Computed new cmap values 2.5496801325515343e-15 - 0.001650735386647284


In [12]:
import matplotlib.pyplot as mp

In [9]:
rc.add_image()

Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x08\x00\x00\x00\x08\x00\x08\x06\x00\x00\x00\xb2\xa7\…

In [10]:
rc.scene.camera.move_forward(0.8)
rc.run()

In [17]:
rc.scene.camera.position[:] = [0.5,0.7,0.1]
rc.scene.camera._update_matrices()

In [18]:
rc.run()

In [21]:
rc.scene.camera.view_matrix

array([[-0.8017837 , -0.53452253, -0.26726124,  0.80178374],
       [-0.59761435,  0.71713716,  0.35856855, -0.23904568],
       [-0.        ,  0.44721356, -0.89442724, -0.22360677],
       [ 0.        ,  0.        ,  0.        ,  1.        ]],
      dtype=float32)

In [39]:
rc.scene.camera.near_plane, rc.scene.camera.far_plane

(4.577636712545434e-05, 20.0)

In [22]:
print("   ".join(dir(rc.scene.camera)))

__class__   __delattr__   __dict__   __dir__   __doc__   __eq__   __format__   __ge__   __getattribute__   __getstate__   __gt__   __hash__   __init__   __init_subclass__   __le__   __lt__   __module__   __ne__   __new__   __reduce__   __reduce_ex__   __repr__   __setattr__   __setstate__   __sizeof__   __str__   __subclasshook__   __weakref__   _add_notifiers   _compute_matrices   _cross_validation_lock   _default_up   _default_view_matrix   _get_trait_default_generator   _map_to_surface   _notify_observers   _notify_trait   _orientation_default   _register_validator   _remove_notifiers   _set_uniforms   _trait_default_generators   _trait_notifiers   _trait_validators   _trait_values   _update_matrices   add_traits   aspect_ratio   class_own_trait_events   class_own_traits   class_trait_names   class_traits   compute_matrices   cross_validation_lock   far_plane   focus   fov   has_trait   held   hold_trait_notifications   hold_traits   move_forward   near_plane   notify_change   obser

In [30]:
import numpy
numpy.linalg.inv(rc.scene.camera.view_matrix).transpose()

array([[-8.0178368e-01, -5.3452253e-01, -2.6726124e-01,  0.0000000e+00],
       [-5.9761435e-01,  7.1713716e-01,  3.5856852e-01,  0.0000000e+00],
       [-5.4423399e-09,  4.4721356e-01, -8.9442718e-01,  0.0000000e+00],
       [ 5.0000000e-01,  6.9999999e-01,  1.0000000e-01,  1.0000000e+00]],
      dtype=float32)

In [31]:
[x for x in dir(rc.scene.camera.view_matrix) if 'off' in x]

[]

In [35]:
rc.scene.camera._update_matrices()
rc.scene.camera.view_matrix

array([[-0.8017837 , -0.53452253, -0.26726124,  0.80178374],
       [-0.59761435,  0.71713716,  0.35856855, -0.23904568],
       [-0.        ,  0.44721356, -0.89442724, -0.22360677],
       [ 0.        ,  0.        ,  0.        ,  1.        ]],
      dtype=float32)

In [49]:
def T44(s):
    return numpy.array( [float(v) for v in s.replace('[',' ').replace(']',' ').replace(',',' ').replace('(',' ').replace(')',' ').split()]).reshape(4,4)

vm = numpy.transpose( numpy.linalg.inv(T44('0.8831300258436215 -0.3249697855549908 0.3383430151928479 0 -0.4048501396250351 -0.8923140822235469 0.199679601139272 0 0.2370183999166184 -0.3133212682565492 -0.9195934215505641 0 1.05853 -0.33372 -0.946352 1') ))
#rc.scene.camera.view_matrix = numpy.transpose( numpy.linalg.inv(T44('') ))
rc.scene.camera.view_matrix = vm

rc.run()

In [45]:
rc.scene.camera.view_matrix = T44('0.8831300258436215 -0.3249697855549908 0.3383430151928479 0 -0.4048501396250351 -0.8923140822235469 0.199679601139272 0 0.2370183999166184 -0.3133212682565492 -0.9195934215505641 0 1.05853 -0.33372 -0.946352 1')
rc.run()

In [44]:
rc.run()


In [ ]:
help(rc.add_image)

In [ ]:
ds.periodicity = [True,True,True]

In [ ]:
rc.run()

In [ ]:
sg.camera.position = [0.5,0.7,0.2]
rc.run()

In [ ]:
rc.add_image(2048,2048)

In [ ]:
[x for x in dir(sg.camera) if x[0]!='_']

In [ ]:
sg.camera.view_matrix

In [ ]:
sg.camera.position

In [ ]:
help(sg.camera.move_forward)

In [ ]:
sg.camera.move_forward(-0.25)

In [ ]:
rc.run()

In [ ]:
rc.image_widget

In [ ]:
rc.image_widget.width

In [ ]:
[x for x in dir(rc.image_widget) if x[0]!='_']

In [ ]:
rc.image_widget.keys